base = [
    '0-day',
    '0day',
    'zero-day',
    'zeroday',
    'antisec',
    'cyberwar',
    'ddos',
    'fuckgov',
    'hacked',
    'hacker',
    'hackers',
    'hacking',
    'priv8',
    'pwn3d',
    'pwned',
    'redeface',
    'rooted',
    'sqli',
    'tangodown',
    'xss',
    'zone-h',
    'zoneh',
    'malware',
    'ddos',
    'cracker',
    'infosec',
    'system vulnerability',
    'network vulnerability',
    'ransomware'
]

pt = [
    'segurança vírus',
    'segurança worm',
    'segurança ataque',
    'segurança intrusão',
    'segurança invasão',
    'intrusão sistema',
    'invasão sistema',
    'invadiu sistema',
    'segurança atacou',
    'atacar sitema',
    'atacou sistema',
    'hackeado',
    'hackeei',
    'hackeamos',
]
en = [
    'security virus',
    'security worm',
    'security attack',
    'security instrusion',
    'security invasion',
    'system virus',
    'system invasion',
    'system attack',
    'system worm',
    'system intrusion',
    'hacked',
    'hacking',
    'site deface',
    'page deface',
    'site defaced',
    'page defaced',
    'site defacement',
    'page defacement',
    'data leak',
    'data leaked',
    'password leak',
    'password leaked',
    'login leak',
    'login leaked',
    'information leak',
    'information leaked',
    'data expose',
    'data exposed',
    'password expose',
    'password exposed',
    'login expose',
    'login exposed',
    'information expose',
    'information exposed',
    'data dox',
    'data doxed',
]